export type CurrencySymbol = string & { readonly brand: unique symbol };

export function isCurrencySymbol(symbol: string): symbol is CurrencySymbol {
  return symbol in symbols.map((s) => s.symbol);
}

export type CurrencyCode = string & { readonly brand: unique symbol };

export function isCurrencyCode(code: string): code is CurrencyCode {
  return code in currencies.map((c) => c.code);
}

export const currencies = [
  {
    code: "AED",
    number: 784,
    minorUnit: 2,
    countries: ["AE"],
  },
  {
    code: "AFN",
    number: 971,
    minorUnit: 2,
    countries: ["AF"],
  },
  {
    code: "ALL",
    number: 8,
    minorUnit: 2,
    countries: ["AL"],
  },
  {
    code: "AMD",
    number: 51,
    minorUnit: 2,
    countries: ["AM"],
  },
  {
    code: "ANG",
    number: 532,
    minorUnit: 2,
    countries: ["CW", "SX"],
  },
  {
    code: "AOA",
    number: 973,
    minorUnit: 2,
    countries: ["AO"],
  },
  {
    code: "ARS",
    number: 32,
    minorUnit: 2,
    countries: ["AR"],
  },
  {
    code: "AUD",
    number: 36,
    minorUnit: 2,
    countries: ["AU", "CC", "CX", "HM", "KI", "NF", "NR", "TV"],
  },
  {
    code: "AWG",
    number: 533,
    minorUnit: 2,
    countries: ["AW"],
  },
  {
    code: "AZN",
    number: 944,
    minorUnit: 2,
    countries: ["AZ"],
  },
  {
    code: "BAM",
    number: 977,
    minorUnit: 2,
    countries: ["BA"],
  },
  {
    code: "BBD",
    number: 52,
    minorUnit: 2,
    countries: ["BB"],
  },
  {
    code: "BDT",
    number: 50,
    minorUnit: 2,
    countries: ["BD"],
  },
  {
    code: "BGN",
    number: 975,
    minorUnit: 2,
    countries: ["BG"],
  },
  {
    code: "BHD",
    number: 48,
    minorUnit: 3,
    countries: ["BH"],
  },
  {
    code: "BIF",
    number: 108,
    minorUnit: 0,
    countries: ["BI"],
  },
  {
    code: "BMD",
    number: 60,
    minorUnit: 2,
    countries: ["BM"],
  },
  {
    code: "BND",
    number: 96,
    minorUnit: 2,
    countries: ["BN"],
  },
  {
    code: "BOB",
    number: 68,
    minorUnit: 2,
    countries: ["BO"],
  },
  {
    code: "BRL",
    number: 986,
    minorUnit: 2,
    countries: ["BR"],
  },
  {
    code: "BSD",
    number: 44,
    minorUnit: 2,
    countries: ["BS"],
  },
  {
    code: "BTC",
    number: null,
    minorUnit: 8,
    countries: [],
  },
  {
    code: "BTN",
    number: 64,
    minorUnit: 2,
    countries: ["BT"],
  },
  {
    code: "BTS",
    number: null,
    minorUnit: 5,
    countries: [],
  },
  {
    code: "BWP",
    number: 72,
    minorUnit: 2,
    countries: ["BW"],
  },
  {
    code: "BYN",
    number: 933,
    minorUnit: 2,
    countries: ["BY"],
  },
  {
    code: "BZD",
    number: 84,
    minorUnit: 2,
    countries: ["BZ"],
  },
  {
    code: "CAD",
    number: 124,
    minorUnit: 2,
    countries: ["CA"],
  },
  {
    code: "CDF",
    number: 976,
    minorUnit: 2,
    countries: ["CD"],
  },
  {
    code: "CHF",
    number: 756,
    minorUnit: 2,
    countries: ["CH", "LI"],
  },
  {
    code: "CLF",
    number: 990,
    minorUnit: 4,
    countries: ["CL"],
  },
  {
    code: "CLP",
    number: 152,
    minorUnit: 0,
    countries: ["CL"],
  },
  {
    code: "CNH",
    number: null,
    minorUnit: 2,
    countries: [],
  },
  {
    code: "CNY",
    number: 156,
    minorUnit: 2,
    countries: ["CN"],
  },
  {
    code: "COP",
    number: 170,
    minorUnit: 2,
    countries: ["CO"],
  },
  {
    code: "CRC",
    number: 188,
    minorUnit: 2,
    countries: ["CR"],
  },
  {
    code: "CUC",
    number: 931,
    minorUnit: 2,
    countries: ["CU"],
  },
  {
    code: "CUP",
    number: 192,
    minorUnit: 2,
    countries: ["CU"],
  },
  {
    code: "CVE",
    number: 132,
    minorUnit: 2,
    countries: ["CV"],
  },
  {
    code: "CZK",
    number: 203,
    minorUnit: 2,
    countries: ["CZ"],
  },
  {
    code: "DASH",
    number: null,
    minorUnit: 8,
    countries: [],
  },
  {
    code: "DJF",
    number: 262,
    minorUnit: 0,
    countries: ["DJ"],
  },
  {
    code: "DKK",
    number: 208,
    minorUnit: 2,
    countries: ["DK", "FO", "GL"],
  },
  {
    code: "DOGE",
    number: null,
    minorUnit: 8,
    countries: [],
  },
  {
    code: "DOP",
    number: 214,
    minorUnit: 2,
    countries: ["DO"],
  },
  {
    code: "DZD",
    number: 12,
    minorUnit: 2,
    countries: ["DZ"],
  },
  {
    code: "EGP",
    number: 818,
    minorUnit: 2,
    countries: ["EG"],
  },
  {
    code: "ERN",
    number: 232,
    minorUnit: 2,
    countries: ["ER"],
  },
  {
    code: "ETB",
    number: 230,
    minorUnit: 2,
    countries: ["ET"],
  },
  {
    code: "ETH",
    number: null,
    minorUnit: 18,
    countries: [],
  },
  {
    code: "EUR",
    number: 978,
    minorUnit: 2,
    countries: [
      "AD",
      "AT",
      "BE",
      "CY",
      "EE",
      "EU",
      "FI",
      "FR",
      "GF",
      "GP",
      "GR",
      "HR",
      "IE",
      "IT",
      "LT",
      "LU",
      "LV",
      "MC",
      "ME",
      "MF",
      "MQ",
      "MT",
      "NL",
      "PF",
      "PM",
      "PT",
      "RE",
      "SI",
      "SK",
      "SM",
      "TF",
      "VA",
    ],
  },
  {
    code: "FJD",
    number: 242,
    minorUnit: 2,
    countries: ["FJ"],
  },
  {
    code: "FKP",
    number: 238,
    minorUnit: 2,
    countries: ["FK"],
  },
  {
    code: "GBP",
    number: 826,
    minorUnit: 2,
    countries: ["GB", "GG", "IM", "JE"],
  },
  {
    code: "GEL",
    number: 981,
    minorUnit: 2,
    countries: ["GE"],
  },
  {
    code: "GGP",
    number: null,
    minorUnit: 2,
    countries: ["GG"],
  },
  {
    code: "GHS",
    number: 936,
    minorUnit: 2,
    countries: ["GH"],
  },
  {
    code: "GIP",
    number: 292,
    minorUnit: 2,
    countries: ["GI"],
  },
  {
    code: "GMD",
    number: 270,
    minorUnit: 2,
    countries: ["GM"],
  },
  {
    code: "GNF",
    number: 324,
    minorUnit: 0,
    countries: ["GN"],
  },
  {
    code: "GTQ",
    number: 320,
    minorUnit: 2,
    countries: ["GT"],
  },
  {
    code: "GYD",
    number: 328,
    minorUnit: 2,
    countries: ["GY"],
  },
  {
    code: "HKD",
    number: 344,
    minorUnit: 2,
    countries: ["HK"],
  },
  {
    code: "HNL",
    number: 340,
    minorUnit: 2,
    countries: ["HN"],
  },
  {
    code: "HRK",
    number: 191,
    minorUnit: 2,
    countries: ["HR"],
  },
  {
    code: "HTG",
    number: 332,
    minorUnit: 2,
    countries: ["HT"],
  },
  {
    code: "HUF",
    number: 348,
    minorUnit: 2,
    countries: ["HU"],
  },
  {
    code: "IDR",
    number: 360,
    minorUnit: 2,
    countries: ["ID"],
  },
  {
    code: "ILS",
    number: 376,
    minorUnit: 2,
    countries: ["IL"],
  },
  {
    code: "IMP",
    number: null,
    minorUnit: 2,
    countries: ["IM"],
  },
  {
    code: "INR",
    number: 356,
    minorUnit: 2,
    countries: ["BT", "IN"],
  },
  {
    code: "IQD",
    number: 368,
    minorUnit: 3,
    countries: ["IQ"],
  },
  {
    code: "IRR",
    number: 364,
    minorUnit: 2,
    countries: ["IR"],
  },
  {
    code: "ISK",
    number: 352,
    minorUnit: 0,
    countries: ["IS"],
  },
  {
    code: "JEP",
    number: null,
    minorUnit: 2,
    countries: ["JE"],
  },
  {
    code: "JMD",
    number: 388,
    minorUnit: 2,
    countries: ["JM"],
  },
  {
    code: "JOD",
    number: 400,
    minorUnit: 3,
    countries: ["JO"],
  },
  {
    code: "JPY",
    number: 392,
    minorUnit: 0,
    countries: ["JP"],
  },
  {
    code: "KES",
    number: 404,
    minorUnit: 2,
    countries: ["KE"],
  },
  {
    code: "KGS",
    number: 417,
    minorUnit: 2,
    countries: ["KG"],
  },
  {
    code: "KHR",
    number: 116,
    minorUnit: 2,
    countries: ["KH"],
  },
  {
    code: "KMF",
    number: 174,
    minorUnit: 0,
    countries: ["KM"],
  },
  {
    code: "KPW",
    number: 408,
    minorUnit: 2,
    countries: ["KP"],
  },
  {
    code: "KRW",
    number: 410,
    minorUnit: 0,
    countries: ["KR"],
  },
  {
    code: "KWD",
    number: 414,
    minorUnit: 3,
    countries: ["KW"],
  },
  {
    code: "KYD",
    number: 136,
    minorUnit: 2,
    countries: ["KY"],
  },
  {
    code: "KZT",
    number: 398,
    minorUnit: 2,
    countries: ["KZ"],
  },
  {
    code: "LAK",
    number: 418,
    minorUnit: 2,
    countries: ["LA"],
  },
  {
    code: "LBP",
    number: 422,
    minorUnit: 2,
    countries: ["LB"],
  },
  {
    code: "LD",
    number: null,
    minorUnit: 8,
    countries: [],
  },
  {
    code: "LKR",
    number: 144,
    minorUnit: 2,
    countries: ["LK"],
  },
  {
    code: "LRD",
    number: 430,
    minorUnit: 2,
    countries: ["LR"],
  },
  {
    code: "LSL",
    number: 426,
    minorUnit: 2,
    countries: ["LS"],
  },
  {
    code: "LTC",
    number: null,
    minorUnit: 8,
    countries: [],
  },
  {
    code: "LYD",
    number: 434,
    minorUnit: 3,
    countries: ["LY"],
  },
  {
    code: "MAD",
    number: 504,
    minorUnit: 2,
    countries: ["EH", "MA"],
  },
  {
    code: "MDL",
    number: 498,
    minorUnit: 2,
    countries: ["MD"],
  },
  {
    code: "MGA",
    number: 969,
    minorUnit: 2,
    countries: ["MG"],
  },
  {
    code: "MKD",
    number: 807,
    minorUnit: 2,
    countries: ["MK"],
  },
  {
    code: "MMK",
    number: 104,
    minorUnit: 2,
    countries: ["MM"],
  },
  {
    code: "MNT",
    number: 496,
    minorUnit: 2,
    countries: ["MN"],
  },
  {
    code: "MOP",
    number: 446,
    minorUnit: 2,
    countries: ["MO"],
  },
  {
    code: "MRU",
    number: 929,
    minorUnit: 2,
    countries: ["MR"],
  },
  {
    code: "MUR",
    number: 480,
    minorUnit: 2,
    countries: ["MU"],
  },
  {
    code: "MVR",
    number: 462,
    minorUnit: 2,
    countries: ["MV"],
  },
  {
    code: "MWK",
    number: 454,
    minorUnit: 2,
    countries: ["MW"],
  },
  {
    code: "MXN",
    number: 484,
    minorUnit: 2,
    countries: ["MX"],
  },
  {
    code: "MYR",
    number: 458,
    minorUnit: 2,
    countries: ["MY"],
  },
  {
    code: "MZN",
    number: 943,
    minorUnit: 2,
    countries: ["MZ"],
  },
  {
    code: "NAD",
    number: 516,
    minorUnit: 2,
    countries: ["NA"],
  },
  {
    code: "NGN",
    number: 566,
    minorUnit: 2,
    countries: ["NG"],
  },
  {
    code: "NIO",
    number: 558,
    minorUnit: 2,
    countries: ["NI"],
  },
  {
    code: "NOK",
    number: 578,
    minorUnit: 2,
    countries: ["BV", "NO"],
  },
  {
    code: "NPR",
    number: 524,
    minorUnit: 2,
    countries: ["NP"],
  },
  {
    code: "NXT",
    number: null,
    minorUnit: 8,
    countries: [],
  },
  {
    code: "NZD",
    number: 554,
    minorUnit: 2,
    countries: ["CK", "NZ", "NU", "PN"],
  },
  {
    code: "OMR",
    number: 512,
    minorUnit: 3,
    countries: ["OM"],
  },
  {
    code: "PAB",
    number: 590,
    minorUnit: 2,
    countries: ["PA"],
  },
  {
    code: "PEN",
    number: 604,
    minorUnit: 2,
    countries: ["PE"],
  },
  {
    code: "PGK",
    number: 598,
    minorUnit: 2,
    countries: ["PG"],
  },
  {
    code: "PHP",
    number: 608,
    minorUnit: 2,
    countries: ["PH"],
  },
  {
    code: "PKR",
    number: 586,
    minorUnit: 2,
    countries: ["PK"],
  },
  {
    code: "PLN",
    number: 985,
    minorUnit: 2,
    countries: ["PL"],
  },
  {
    code: "PYG",
    number: 600,
    minorUnit: 0,
    countries: ["PY"],
  },
  {
    code: "QAR",
    number: 634,
    minorUnit: 2,
    countries: ["QA"],
  },
  {
    code: "RON",
    number: 946,
    minorUnit: 2,
    countries: ["RO"],
  },
  {
    code: "RSD",
    number: 941,
    minorUnit: 2,
    countries: ["RS"],
  },
  {
    code: "RUB",
    number: 643,
    minorUnit: 2,
    countries: ["RU"],
  },
  {
    code: "RWF",
    number: 646,
    minorUnit: 0,
    countries: ["RW"],
  },
  {
    code: "SAR",
    number: 682,
    minorUnit: 2,
    countries: ["SA"],
  },
  {
    code: "SBD",
    number: 90,
    minorUnit: 2,
    countries: ["SB"],
  },
  {
    code: "SCR",
    number: 690,
    minorUnit: 2,
    countries: ["SC"],
  },
  {
    code: "SDG",
    number: 938,
    minorUnit: 2,
    countries: ["SD"],
  },
  {
    code: "SEK",
    number: 752,
    minorUnit: 2,
    countries: ["SE"],
  },
  {
    code: "SGD",
    number: 702,
    minorUnit: 2,
    countries: ["SG"],
  },
  {
    code: "SHP",
    number: 654,
    minorUnit: 2,
    countries: ["SH"],
  },
  {
    code: "SLE",
    number: 925,
    minorUnit: 2,
    countries: ["SL"],
  },
  {
    code: "SLL",
    number: 694,
    minorUnit: 2,
    countries: ["SL"],
  },
  {
    code: "SOS",
    number: 706,
    minorUnit: 2,
    countries: ["SO"],
  },
  {
    code: "SRD",
    number: 968,
    minorUnit: 2,
    countries: ["SR"],
  },
  {
    code: "SSP",
    number: 728,
    minorUnit: 2,
    countries: ["SS"],
  },
  {
    code: "STD",
    number: 678,
    minorUnit: 2,
    countries: ["ST"],
  },
  {
    code: "STN",
    number: 930,
    minorUnit: 2,
    countries: ["ST"],
  },
  {
    code: "STR",
    number: null,
    minorUnit: 6,
    countries: [],
  },
  {
    code: "SVC",
    number: 222,
    minorUnit: 2,
    countries: ["SV"],
  },
  {
    code: "SYP",
    number: 760,
    minorUnit: 2,
    countries: ["SY"],
  },
  {
    code: "SZL",
    number: 748,
    minorUnit: 2,
    countries: ["SZ"],
  },
  {
    code: "THB",
    number: 764,
    minorUnit: 2,
    countries: ["TH"],
  },
  {
    code: "TJS",
    number: 972,
    minorUnit: 2,
    countries: ["TJ"],
  },
  {
    code: "TMT",
    number: 934,
    minorUnit: 2,
    countries: ["TM"],
  },
  {
    code: "TND",
    number: 788,
    minorUnit: 3,
    countries: ["TN"],
  },
  {
    code: "TOP",
    number: 776,
    minorUnit: 2,
    countries: ["TO"],
  },
  {
    code: "TRY",
    number: 949,
    minorUnit: 2,
    countries: ["TR"],
  },
  {
    code: "TTD",
    number: 780,
    minorUnit: 2,
    countries: ["TT"],
  },
  {
    code: "TWD",
    number: 901,
    minorUnit: 2,
    countries: ["TW"],
  },
  {
    code: "TZS",
    number: 834,
    minorUnit: 2,
    countries: ["TZ"],
  },
  {
    code: "UAH",
    number: 980,
    minorUnit: 2,
    countries: ["UA"],
  },
  {
    code: "UGX",
    number: 800,
    minorUnit: 0,
    countries: ["UG"],
  },
  {
    code: "USD",
    number: 840,
    minorUnit: 2,
    countries: ["AS", "BQ", "EC", "FM", "GU", "HT", "IO", "MH", "MP", "PA", "PR", "PW", "TC", "US", "VI"],
  },
  {
    code: "UYU",
    number: 858,
    minorUnit: 2,
    countries: ["UY"],
  },
  {
    code: "UZS",
    number: 860,
    minorUnit: 2,
    countries: ["UZ"],
  },
  {
    code: "VEF_BLKMKT",
    number: null,
    minorUnit: 2,
    countries: ["VE"],
  },
  {
    code: "VEF_DICOM",
    number: null,
    minorUnit: 2,
    countries: ["VE"],
  },
  {
    code: "VEF_DIPRO",
    number: null,
    minorUnit: 2,
    countries: ["VE"],
  },
  {
    code: "VES",
    number: 928,
    minorUnit: 2,
    countries: ["VE"],
  },
  {
    code: "VND",
    number: 704,
    minorUnit: 0,
    countries: ["VN"],
  },
  {
    code: "VUV",
    number: 548,
    minorUnit: 0,
    countries: ["VU"],
  },
  {
    code: "WST",
    number: 882,
    minorUnit: 2,
    countries: ["WS"],
  },
  {
    code: "XAF",
    number: 950,
    minorUnit: 0,
    countries: ["CF", "CG", "CM", "GA", "GQ", "TD"],
  },
  {
    code: "XAG",
    number: 961,
    minorUnit: null,
    countries: [],
  },
  {
    code: "XAU",
    number: 959,
    minorUnit: null,
    countries: [],
  },
  {
    code: "XCD",
    number: 951,
    minorUnit: 2,
    countries: ["AG", "AI", "DM", "GD", "KN", "LC", "MS", "VC"],
  },
  {
    code: "XCG",
    number: 532,
    minorUnit: 2,
    countries: ["CW", "SX"],
  },
  {
    code: "XDR",
    number: 960,
    minorUnit: null,
    countries: [],
  },
  {
    code: "XMR",
    number: null,
    minorUnit: 12,
    countries: [],
  },
  {
    code: "XOF",
    number: 952,
    minorUnit: 0,
    countries: ["BF", "BJ", "CI", "GW", "ML", "NE", "SN", "TG"],
  },
  {
    code: "XPD",
    number: 964,
    minorUnit: null,
    countries: [],
  },
  {
    code: "XPF",
    number: 953,
    minorUnit: 0,
    countries: ["NC", "WF"],
  },
  {
    code: "XPT",
    number: 962,
    minorUnit: null,
    countries: [],
  },
  {
    code: "XRP",
    number: null,
    minorUnit: 6,
    countries: [],
  },
  {
    code: "YER",
    number: 886,
    minorUnit: 2,
    countries: ["YE"],
  },
  {
    code: "ZAR",
    number: 710,
    minorUnit: 2,
    countries: ["LS", "NA", "ZA"],
  },
  {
    code: "ZMW",
    number: 967,
    minorUnit: 2,
    countries: ["ZM"],
  },
  {
    code: "ZWG",
    number: 924,
    minorUnit: 2,
    countries: ["ZW"],
  },
  {
    code: "ZWL" as CurrencyCode,
    number: 932,
    minorUnit: 2,
    countries: ["ZW"],
  },
] as const as {
  code: CurrencyCode;
  number: number;
  minorUnit: number;
  countries: string[];
}[];

export const symbols = [
  {
    symbol: "؋",
    default: "AFN",
    codes: ["AFN"],
    alternatives: ["Af", "Afs"],
  },
  {
    symbol: "Ar",
    default: "MGA",
    codes: ["MGA"],
    alternatives: [],
  },
  {
    symbol: "฿",
    default: "THB",
    codes: ["THB"],
    alternatives: [],
  },
  {
    symbol: "B/.",
    default: "PAB",
    codes: ["PAB"],
    alternatives: [],
  },
  {
    symbol: "Br",
    default: "BYN",
    codes: ["BYN", "ETB"],
    alternatives: [],
  },
  {
    symbol: "₿",
    default: "BTC",
    codes: ["BTC"],
    alternatives: [],
  },

  {
    symbol: "BTS",
    default: "BTS",
    codes: ["BTS"],
    alternatives: [],
  },
  {
    symbol: "Bs",
    default: "BOB",
    codes: ["BOB", "VEF_BLKMKT", "VEF_DICOM", "VEF_DIPRO"],
    alternatives: [],
  },
  {
    symbol: "Bs.S",
    default: "VES",
    codes: ["VES"],
    alternatives: [],
  },
  {
    symbol: "C$",
    default: "NIO",
    codes: ["NIO"],
    alternatives: [],
  },
  {
    symbol: "CF",
    default: "KMF",
    codes: ["KMF"],
    alternatives: [],
  },
  {
    symbol: "CFA",
    default: "XOF",
    codes: ["XOF"],
    alternatives: [],
  },
  {
    symbol: "CFP",
    default: "XPF",
    codes: ["XPF"],
    alternatives: [],
  },
  {
    symbol: "CHF",
    default: "CHF",
    codes: ["CHF"],
    alternatives: [],
  },
  {
    symbol: "D",
    default: "GMD",
    codes: ["GMD"],
    alternatives: [],
  },
  {
    symbol: "DASH",
    default: "DASH",
    codes: ["DASH"],
    alternatives: [],
  },
  {
    symbol: "Db",
    default: "STN",
    codes: ["STD", "STN"],
    alternatives: [],
  },
  {
    symbol: "FC",
    default: "CDF",
    codes: ["CDF"],
    alternatives: [],
  },
  {
    symbol: "FCFA",
    default: "XAF",
    codes: ["XAF"],
    alternatives: [],
  },
  {
    symbol: "FBu",
    default: "BIF",
    codes: ["BIF"],
    alternatives: [],
  },
  {
    symbol: "FG",
    default: "GNF",
    codes: ["GNF"],
    alternatives: [],
  },
  {
    symbol: "FRw",
    default: "RWF",
    codes: ["RWF"],
    alternatives: [],
  },
  {
    symbol: "Fdj",
    default: "DJF",
    codes: ["DJF"],
    alternatives: [],
  },
  {
    symbol: "Ft",
    default: "HUF",
    codes: ["HUF"],
    alternatives: [],
  },
  {
    symbol: "G",
    default: "HTG",
    codes: ["HTG"],
    alternatives: [],
  },
  {
    symbol: "K",
    default: "MMK",
    codes: ["MMK", "MWK", "PGK"],
    alternatives: [],
  },
  {
    symbol: "KM",
    default: "BAM",
    codes: ["BAM"],
    alternatives: [],
  },
  {
    symbol: "KSh",
    default: "KES",
    codes: ["KES"],
    alternatives: [],
  },
  {
    symbol: "Kč",
    default: "CZK",
    codes: ["CZK"],
    alternatives: [],
  },
  {
    symbol: "Kz",
    default: "AOA",
    codes: ["AOA"],
    alternatives: [],
  },
  {
    symbol: "L",
    default: "ALL",
    codes: ["ALL", "LSL", "SZL"],
    alternatives: [],
  },
  {
    symbol: "LD",
    default: "LD",
    codes: ["LD"],
    alternatives: [],
  },
  {
    symbol: "Le",
    default: "SLL",
    codes: ["SLE", "SLL"],
    alternatives: [],
  },
  {
    symbol: "MOP$",
    default: "MOP",
    codes: ["MOP"],
    alternatives: [],
  },
  {
    symbol: "MT",
    default: "MZN",
    codes: ["MZN"],
    alternatives: [],
  },
  {
    symbol: "NT$",
    default: "TWD",
    codes: ["TWD"],
    alternatives: [],
  },
  {
    symbol: "NXT",
    default: "NXT",
    codes: ["NXT"],
    alternatives: [],
  },
  {
    symbol: "Nfk",
    default: "ERN",
    codes: ["ERN"],
    alternatives: [],
  },
  {
    symbol: "Nu.",
    default: "BTN",
    codes: ["BTN"],
    alternatives: [],
  },
  {
    symbol: "P",
    default: "BWP",
    codes: ["BWP"],
    alternatives: [],
  },
  {
    symbol: "Q",
    default: "GTQ",
    codes: ["GTQ"],
    alternatives: [],
  },
  {
    symbol: "R",
    default: "ZAR",
    codes: ["ZAR"],
    alternatives: [],
  },
  {
    symbol: "R$",
    default: "BRL",
    codes: ["BRL"],
    alternatives: [],
  },
  {
    symbol: "RM",
    default: "MYR",
    codes: ["MYR"],
    alternatives: [],
  },
  {
    symbol: "Rf",
    default: "MVR",
    codes: ["MVR"],
    alternatives: [],
  },
  {
    symbol: "Rp",
    default: "IDR",
    codes: ["IDR"],
    alternatives: [],
  },
  {
    symbol: "S",
    default: "SOS",
    codes: ["SOS"],
    alternatives: [],
  },
  {
    symbol: "S/",
    default: "PEN",
    codes: ["PEN"],
    alternatives: [],
  },
  {
    symbol: "SS£",
    default: "SSP",
    codes: ["SSP"],
    alternatives: [],
  },
  {
    symbol: "STR",
    default: "STR",
    codes: ["STR"],
    alternatives: [],
  },
  {
    symbol: "T",
    default: "TMT",
    codes: ["TMT", "WST"],
    alternatives: [],
  },
  {
    symbol: "T$",
    default: "TOP",
    codes: ["TOP"],
    alternatives: [],
  },
  {
    symbol: "TSh",
    default: "TZS",
    codes: ["TZS"],
    alternatives: [],
  },
  {
    symbol: "UF",
    default: "CLF",
    codes: ["CLF"],
    alternatives: [],
  },
  {
    symbol: "UM",
    default: "MRU",
    codes: ["MRU"],
    alternatives: [],
  },
  {
    symbol: "USh",
    default: "UGX",
    codes: ["UGX"],
    alternatives: [],
  },
  {
    symbol: "VT",
    default: "VUV",
    codes: ["VUV"],
    alternatives: [],
  },
  {
    symbol: "XAG",
    default: "XAG",
    codes: ["XAG"],
    alternatives: [],
  },
  {
    symbol: "XAU",
    default: "XAU",
    codes: ["XAU"],
    alternatives: [],
  },
  {
    symbol: "XDR",
    default: "XDR",
    codes: ["XDR"],
    alternatives: [],
  },
  {
    symbol: "XPD",
    default: "XPD",
    codes: ["XPD"],
    alternatives: [],
  },
  {
    symbol: "XPT",
    default: "XPT",
    codes: ["XPT"],
    alternatives: [],
  },
  {
    symbol: "XRP",
    default: "XRP",
    codes: ["XRP"],
    alternatives: [],
  },
  {
    symbol: "ZK",
    default: "ZMW",
    codes: ["ZMW"],
    alternatives: [],
  },
  {
    symbol: "ZWG",
    default: "ZWG",
    codes: ["ZWG"],
    alternatives: [],
  },
  {
    symbol: "ZWL",
    default: "ZWL",
    codes: ["ZWL"],
    alternatives: [],
  },
  {
    symbol: "$",
    default: "USD",
    codes: [
      "ARS",
      "AUD",
      "BSD",
      "BBD",
      "BMD",
      "BND",
      "BOB",
      "CAD",
      "CLP",
      "COP",
      "CRC",
      "CUC",
      "CUP",
      "CVE",
      "DOP",
      "FJD",
      "GYD",
      "HKD",
      "JMD",
      "KYD",
      "LRD",
      "MXN",
      "NAD",
      "NZD",
      "PAB",
      "SBD",
      "SRD",
      "TTD",
      "USD",
      "UYU",
      "XCD",
    ],
    alternatives: ["＄", "💲"],
  },
  {
    symbol: "¥",
    default: "JPY",
    codes: ["CNH", "CNY", "JPY"],
    alternatives: ["￥", "💴"],
  },
  {
    symbol: "£",
    default: "GBP",
    codes: ["EGP", "FKP", "GBP", "GIP", "IMP", "JEP", "SHP", "SYP"],
    alternatives: ["₤", "💷"],
  },
  {
    symbol: "€",
    default: "EUR",
    codes: ["EUR"],
    alternatives: [],
  },
  {
    symbol: "ɱ",
    default: "XMR",
    codes: ["XMR"],
    alternatives: [],
  },
  {
    symbol: "с",
    default: "KGS",
    codes: ["KGS"],
    alternatives: [],
  },
  {
    symbol: "ден",
    default: "MKD",
    codes: ["MKD"],
    alternatives: [],
  },
  {
    symbol: "дин.",
    default: "RSD",
    codes: ["RSD"],
    alternatives: [],
  },
  {
    symbol: "лв",
    default: "BGN",
    codes: ["BGN"],
    alternatives: [],
  },
  {
    symbol: "kr",
    default: "DKK",
    codes: ["DKK", "ISK", "NOK", "SEK"],
    alternatives: [],
  },
  {
    symbol: "kn",
    default: "HRK",
    codes: ["HRK"],
    alternatives: [],
  },
  {
    symbol: "lei",
    default: "RON",
    codes: ["RON"],
    alternatives: [],
  },
  {
    symbol: "so'm",
    default: "UZS",
    codes: ["UZS"],
    alternatives: [],
  },
  {
    symbol: "zł",
    default: "PLN",
    codes: ["PLN"],
    alternatives: [],
  },
  {
    symbol: "ƒ",
    default: "ANG",
    codes: ["ANG", "AWG", "XCG"],
    alternatives: [],
  },
  {
    symbol: "Ð",
    default: "DOGE",
    codes: ["DOGE"],
    alternatives: [],
  },
  {
    symbol: "Ł",
    default: "LTC",
    codes: ["LTC"],
    alternatives: [],
  },
  {
    symbol: "Ξ",
    default: "ETH",
    codes: ["ETH"],
    alternatives: [],
  },
  {
    symbol: "ЅМ",
    default: "TJS",
    codes: ["TJS"],
    alternatives: [],
  },
  {
    symbol: "৳",
    default: "BDT",
    codes: ["BDT"],
    alternatives: [],
  },
  {
    symbol: "៛",
    default: "KHR",
    codes: ["KHR"],
    alternatives: [],
  },
  {
    symbol: "֏",
    default: "AMD",
    codes: ["AMD"],
    alternatives: [],
  },
  {
    symbol: "₡",
    default: "CRC",
    codes: ["CRC"],
    alternatives: [],
  },
  {
    symbol: "₨",
    default: "SCR",
    codes: ["LKR", "MUR", "NPR", "PKR", "SCR"],
    alternatives: [],
  },
  {
    symbol: "₩",
    default: "KRW",
    codes: ["KPW", "KRW"],
    alternatives: [],
  },
  {
    symbol: "₪",
    default: "ILS",
    codes: ["ILS"],
    alternatives: [],
  },
  {
    symbol: "₫",
    default: "VND",
    codes: ["VND"],
    alternatives: [],
  },
  {
    symbol: "₭",
    default: "LAK",
    codes: ["LAK"],
    alternatives: [],
  },
  {
    symbol: "₮",
    default: "MNT",
    codes: ["MNT"],
    alternatives: [],
  },
  {
    symbol: "₯",
    default: "GRD",
    codes: ["GRD"],
    alternatives: [],
  },
  {
    symbol: "₱",
    default: "PHP",
    codes: ["PHP"],
    alternatives: [],
  },
  {
    symbol: "₲",
    default: "PYG",
    codes: ["PYG"],
    alternatives: [],
  },
  {
    symbol: "₴",
    default: "UAH",
    codes: ["UAH"],
    alternatives: [],
  },
  {
    symbol: "₵",
    default: "GHS",
    codes: ["GHS"],
    alternatives: [],
  },
  {
    symbol: "₶",
    default: "ARA",
    codes: ["ARA"],
    alternatives: [],
  },
  {
    symbol: "₷",
    default: "GNS",
    codes: ["GNS"],
    alternatives: [],
  },
  {
    symbol: "₸",
    default: "KZT",
    codes: ["KZT"],
    alternatives: [],
  },
  {
    symbol: "₹",
    default: "INR",
    codes: ["INR"],
    alternatives: [],
  },
  {
    symbol: "₺",
    default: "TRY",
    codes: ["TRY"],
    alternatives: [],
  },
  {
    symbol: "₼",
    default: "AZN",
    codes: ["AZN"],
    alternatives: [],
  },
  {
    symbol: "₽",
    default: "RUB",
    codes: ["RUB"],
    alternatives: [],
  },
  {
    symbol: "₾",
    default: "GEL",
    codes: ["GEL"],
    alternatives: [],
  },
  {
    symbol: "₿",
    default: "BTC",
    codes: ["BTC"],
    alternatives: [],
  },
  {
    symbol: "﷼",
    default: "IRR",
    codes: ["IRR", "YER"],
    alternatives: [],
  },
  {
    symbol: "＄",
    default: "USD",
    codes: ["USD"],
    alternatives: [],
  },
  {
    symbol: "￥",
    default: "JPY",
    codes: ["JPY"],
    alternatives: [],
  },
  {
    symbol: "د.إ",
    default: "AED",
    codes: ["AED"],
    alternatives: [],
  },
  {
    symbol: "د.ا",
    default: "JOD",
    codes: ["JOD"],
    alternatives: [],
  },
  {
    symbol: "د.ب",
    default: "BHD",
    codes: ["BHD"],
    alternatives: [],
  },
  {
    symbol: "د.ت",
    default: "TND",
    codes: ["TND"],
    alternatives: [],
  },
  {
    symbol: "د.ج",
    default: "DZD",
    codes: ["DZD"],
    alternatives: [],
  },
  {
    symbol: "د.ك",
    default: "KWD",
    codes: ["KWD"],
    alternatives: [],
  },
  {
    symbol: "د.م.",
    default: "MAD",
    codes: ["MAD"],
    alternatives: [],
  },
  {
    symbol: "ر.س",
    default: "SAR",
    codes: ["SAR"],
    alternatives: [],
  },
  {
    symbol: "ر.ع.",
    default: "OMR",
    codes: ["OMR"],
    alternatives: [],
  },
  {
    symbol: "ر.ق",
    default: "QAR",
    codes: ["QAR"],
    alternatives: [],
  },
  {
    symbol: "ع.د",
    default: "IQD",
    codes: ["IQD"],
    alternatives: [],
  },
  {
    symbol: "ج.س.",
    default: "SDG",
    codes: ["SDG"],
    alternatives: [],
  },
  {
    symbol: "ل.د",
    default: "LYD",
    codes: ["LYD"],
    alternatives: [],
  },
  {
    symbol: "ل.ل",
    default: "LBP" as CurrencyCode,
    codes: ["LBP"] as CurrencyCode[],
    alternatives: [],
  },
] as const as {
  symbol: string;
  default: CurrencyCode;
  codes: CurrencyCode[];
  alternatives: CurrencyCode[];
}[];
